version: '2'
services:
  postgresql:
    image: mdillon/postgis:9.6-alpine
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: osm-roads-dev
    volumes:
      - ./data/postgresql-dev:/var/lib/postgresql/data
